name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    name: Python ${{ matrix.python-version}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip and install dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: linters
        run: |
          black --check --verbose .
          flake8 tests/ astragalus/ setup.py

      - name: Run tests
        run: tox